runtime: python27
api_version: 1
threadsafe: true

service: ohif-caip

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /callback
  static_files: www/index.html
  upload: www/index.html

- url: /projects/(.*)
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
